E5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("cars.urls", namespace="cars")),
]

cars/urls.py
from django.urls import path  
from . import views
  
app_name = "cars"  
urlpatterns = [  
    path("", views.index.as_view(), name="cars_list"),  
    path("<slug:slug>/", views.CarDetail.as_view(), name="car_detail")  
]

cars/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Car(models.Model):
    TRANSMISSION_MANUAL = 0
    TRANSMISSION_AUTO = 1
    TRANSMISSION_ROBOT = 2
    TRANSMISSION_CHOICES = (
        (TRANSMISSION_MANUAL, "Manual"),
        (TRANSMISSION_AUTO, "Automatic"),
        (TRANSMISSION_ROBOT, "Robot"),
    )
    
    maker = models.CharField(max_length=127)
    car_model = models.CharField(max_length=64)
    year = models.IntegerField()    
    transmission = models.PositiveSmallIntegerField(choices=TRANSMISSION_CHOICES, default=TRANSMISSION_MANUAL)
    color = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ("maker",)

    def __str__(self):
        return "{} {}".format(self.maker, self.car_model)

    def get_absolute_url(self):
        return reverse("cars:car_detail", args=[self.slug])

cars/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.db.models import Q
from .models import Car

# Create your views here.

class index(ListView):    
    model = Car    
    context_object_name = "cars"
    template_name = "index.html"  
    paginate_by = 12

    def get_queryset(self):
        cars = super().get_queryset()
        query_dict = dict(self.request.GET.lists())
                
        maker_Q = Q(maker__icontains=query_dict.get("maker", [""])[0])
        model_Q = Q(car_model__icontains=query_dict.get("model", [""])[0])

        year_Q = Q(year__isnull=False)
        if "year" in query_dict:
            try:
                query_dict["year"] = [int(x) for x in query_dict["year"]]
                year_Q = Q(year__in=query_dict["year"])
            except ValueError:            
                pass

        transmission_Q = Q(transmission__isnull=False)
        if "transmission" in query_dict:
            try:
                query_dict["transmission"] = [int(x) for x in query_dict["transmission"]]
                transmission_Q = Q(transmission__in=query_dict["transmission"])
            except ValueError:            
                pass            

        color_Q = Q(color__icontains=query_dict.get("color", [""])[0])

        cars = cars.filter(maker_Q & model_Q & year_Q & transmission_Q & color_Q)

        return cars

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        r_copy = self.request.GET.copy()
        if "page" in r_copy:
            r_copy.pop("page")
        context["filter"] = r_copy.urlencode()
        return context


class CarDetail(DetailView):
    model = Car
    template_name = "car_detail.html"   

cars/templates/base_cars.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <meta charset="utf-8">
    <title>Автомобили.</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">       
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
</head>

<body>
    <div class="body-wrapper">
        <header>
            <div class="wrapperout">
                <h1>База автомобилей.</h1>            
            </div>
        </header>
        <main>
            
            <div class="wrapperout">
                {% block main_content %}
                {% endblock main_content %}
            </div>
            
            
        </main>        

        <aside class="main-filter">
            <div class="wrapperin">
                <h1>Фильтр</h1>
                <form action="" class="form-group">
                    <label for="filter-maker" class="col-form-label mt-3">Производитель:</label>
                    <input id="filter-maker" class="form-control search-form" name="maker" type="search" placeholder="...">
                    <label for="filter-model" class="col-form-label mt-3">Модель:</label>
                    <input id="filter-model" class="form-control search-form" name="model" type="search" placeholder="...">
                    <label for="filter-year" class="col-form-label mt-3">Год:</label>
                    <input id="filter-year" class="form-control search-form" name="year" type="number" placeholder="...">
                    
                    <div class="mt-3">Коробка передач:</div>
                    <fieldset>
                    <div class="form-check">                            
                        <input id="filter-transmission" class="form-check-input" name="transmission" type="checkbox" value="0">
                        <label for="filter-transmission" class="form-check-label">Ручная</label>
                    </div>
                    <div class="form-check">                            
                        <input id="filter-transmission" class="form-check-input" name="transmission" type="checkbox" value="1">
                        <label for="filter-transmission" class="form-check-label">Автоматическая</label>
                    </div>
                    <div class="form-check">                            
                        <input id="filter-transmission" class="form-check-input" name="transmission" type="checkbox" value="2">
                        <label for="filter-transmission" class="form-check-label">Робот</label>
                    </div>
                    </fieldset>
                    
                    <label for="filter-color" class="col-form-label mt-3">Цвет:</label>
                    <input id="filter-color" class="form-control search-form" name="color" type="search" placeholder="...">
                    <div class="form-group filter-button mt-3">
                        <button type="submit" class="btn btn-outline-primary btn-sm btn-block">Применить</button>                    
                    </div>
                    <div class="form-group filter-button">
                        <button type="reset" class="btn btn-outline-primary btn-sm btn-block">Очистить</button>                    
                    </div>
                    <div class="form-group filter-button">
                        <a href="/" class="btn btn-outline-primary btn-sm btn-block">Сбросить</a>                   
                    </div>
                </form>                
            </div>
        </aside>

    </div>
</body>

cars/templates/car_detail.html
{% extends 'base_cars.html' %}

{% block main_content %} 

<div class="wrapperin">                
    <h1>{{ object.maker }}</h1>
    <h1>{{ object.car_model }}</h1>
    <h1>{{ object.year }}</h1>
    <h1>{{ object.get_transmission_display }}</h1>
    <h1>{{ object.color }}</h1>
</div>

{% endblock main_content %} 

cars/templates/index.html
{% extends 'base_cars.html' %}

{% block main_content %} 

<div class="wrapperin">

    <table class="table table-bordered table-hover mt-3">
        <tr>            
            <th scope="col">Производитель</th>
            <th scope="col">Модель</th>                
            <th scope="col">Год</th>
            <th scope="col">Коробка передач</th> 
            <th scope="col">Цвет</th>                                 
            <th scope="col"></th> 
        </tr>
        {% for car in cars %}
        <tr>            
            <td>{{ car.maker }}</td>
            <td>{{ car.car_model }}</td>
            <td>{{ car.year }}</td>
            <td>{{ car.get_transmission_display }}</td>
            <td>{{ car.color }}</td>                        
            <td><a href="{{ car.get_absolute_url }}">Подробнее</a></td> 
        </tr>        
        {% endfor %}
    </table>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?{{filter}}&page=1">&laquo; first</a>
                <a href="?{{filter}}&page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?{{filter}}&page={{ page_obj.next_page_number }}">next</a>
                <a href="?{{filter}}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</div>

{% endblock main_content %} 